[Data]

epsilon = -15
delta   = -13
gamma   = 0.6

fe_macro_degree = 1
nonlinear = true
damped    = true
periodic  = true 
end_time  = 1.

[Space_Discretization]
; 2^(initial_refinement + p  -1) + 1: numbers of dofs
initial_refinement = 2
; refinement_steps  : error calculations 
refinement_steps = 3
;  reference solution 
level_ref   = 2        
; solution with origin coefficient
level_origin = 10  
; level_micro :  mico grid h = 2^{-level_micro_bound} / without upper bound
level_micro_upper_bound = 4
level_micro_lower_bound = 1
order_micro             = 1


[Time_Integration]
initial_time_step_macro = 1000. 
theta = 0.5
refinement_rate_time = 0.5

[Calculation_Mode]
exactSol = true
longtime = false
;coefficient_type = origin
;coefficient_type = exact_hom
coefficient_type = hmm_hom

;nur relevant wenn calculation_mode = error...
;ref_coefficient_type = origin
;ref_coefficient_type = exact_hom
;ref_coefficient_type = hmm_hom

example          = 10
calculation_mode = error_calculation_space 
;calculation_mode = error_calculation_time 
;calculation_mode = reference 

timeintegrationmode = IMEXR
;timeintegrationmode = IMPMID,IMEXE,IMEXR,EXPMID,IMEXARS3

[Output]
newton_cg_steps = true
cycle           = true


